spring:
  datasource:
    name: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myLocalHost?serverTimezone=UTC&useUnicode=true@characterEncodeing=utf-8


mybatis:
#  mapper的所在路径
  config-locations: classpath:mapper/*.xml
#  实体类所在路径
  type-aliases-package: com.dy.entity
